DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE product (
  ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  CATEGORY VARCHAR(250) NOT NULL,
  PRODUCT_ID VARCHAR(250) NOT NULL
);

INSERT INTO PRODUCT ( CATEGORY, PRODUCT_ID) VALUES ('Dress', 'D12');